name: Jobdori

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Jobdori Script
        run: node jobdori.js